### ISSUE TITLE
[koffi] When registering a class function as callback the scope is not set.

### ISSUE THREAD

**Issue by nwrkbiz** [Koromix/rygel#11]
-> This means you can not access the member variables of the class within the callback.

This can easily be worked around by binding the classs instance  to the class function thus the behaviour is a matter of taste. Still I wanted to document this here, because there is the possibility  to read and set the scope in c++ by using the v8 / napi api.

**Comment by Koromix** [comment]
Hi,

Do you mean something like this?

```js
// Suppose CallIt (below) is a C function that just calls the void() callback passed to it

class FortuneTeller {
    constructor(k) { this.msg = msg; }
    print() { console.log(this.msg); }
}

let teller = new FortuneTeller('You will lead a happy life');

teller.print(); // Prints 'You will lead a happy life'
CallIt(teller.print); // Prints 'undefined'
```

As far as I know, the only way for this to work is to use bind() in JS, because `this` depends on how the function is called and nothing else. Which means that once the callback gets to Koffi, the context is lost and we can only do a function call (instead of a method invocation), and this is not defined (or defined as the global object depending on strictness).

Or is there something I've missed?

**Comment by Koromix** [comment]
Same thing without Koffi:

```js
class FortuneTeller {
    constructor(msg) { this.msg = msg; }
    print() { console.log(this.msg); }
}

function CallIt(cb) {
    cb();
}

let teller = new FortuneTeller('You will lead a happy life');

teller.print(); // Prints 'You will lead a happy life'
CallIt(teller.print); // Does not work
```

**Comment by Koromix** [comment]
Koffi 2.2 will introduce a way to explicitly bind this in `koffi.register()`.

Details here: https://github.com/Koromix/rygel/commit/4653349acf7487b21af024226e83b1a50153c795#diff-6a5f9429d19f881f66d27e7a429225c2ae15cbaacebc340385e0318b2dc916c2L408

**Comment by nwrkbiz** [comment]
> Same thing without Koffi:
> 
> ```js
> class FortuneTeller {
>     constructor(msg) { this.msg = msg; }
>     print() { console.log(this.msg); }
> }
> 
> function CallIt(cb) {
>     cb();
> }
> 
> let teller = new FortuneTeller('You will lead a happy life');
> 
> teller.print(); // Prints 'You will lead a happy life'
> CallIt(teller.print); // Does not work
> ```

O.k. then it makes sense the way it is, as you can use `bind` for it to work. Sorry for the noise, it works as expected, I was mixing some things up in my head.

**Comment by Koromix** [comment]
No problem!

Let's say it makes sense in the context of Javascript... It's just that `this` in Javascript is not intuitive and kind of annoying 😅
