### ISSUE TITLE
Problem decoding opaque output parameter (void *)

### ISSUE THREAD

**Issue by insraq** [Koromix/rygel#18]
While working on binding to Steamworks SDK, the header file is here (https://github.com/Facepunch/Facepunch.Steamworks/blob/master/Generator/steam_sdk/steam_api.h)

Here's the relevant function:

`bool SteamAPI_ManualDispatch_GetAPICallResult( HSteamPipe hSteamPipe, SteamAPICall_t hSteamAPICall, void *pCallback, int cubCallback, int iCallbackExpected, bool *pbFailed );`

`pCallback`'s type depends on some tag. The following code works:

```typescript
const SteamAPI_ManualDispatch_GetAPICallResult = steamLib.cdecl(
    "bool SteamAPI_ManualDispatch_GetAPICallResult(HSteamPipe hSteamPipe, SteamAPICall_t hSteamAPICall, _Out_ void *pCallback, int cubCallback, int iCallbackExpected, _Out_ bool *pbFailed)"
);

const RemoteStorageFileReadAsyncComplete_t = koffi.struct("RemoteStorageFileReadAsyncComplete_t", {
    m_hFileReadAsync: "SteamAPICall_t",
    m_eResult: "uint32",
    m_nOffset: "uint32",
    m_cubRead: "uint32",
});

const ptr: any = {};
const fail = [false];
if (completed.m_iCallback === 1332) {
    if (
        SteamAPI_ManualDispatch_GetAPICallResult(
            pipe,
            completed.m_hAsyncCall, // call id
            koffi.as(ptr, "RemoteStorageFileReadAsyncComplete_t *"),
            completed.m_cubParam, // param size
            completed.m_iCallback, // callback type
            fail
        )
    ) {
        console.log(ptr); // we get a js object of RemoteStorageFileReadAsyncComplete_t
    }
}
```

However, this is a bit inconvenient - it's easier for this function to dispatch an opaque point to registered callbacks and for the callee to figure out the type.

```typescript

const SteamAPI_ManualDispatch_GetAPICallResult = steamLib.cdecl(
    "bool SteamAPI_ManualDispatch_GetAPICallResult(HSteamPipe hSteamPipe, SteamAPICall_t hSteamAPICall, _Out_ void **pCallback, int cubCallback, int iCallbackExpected, _Out_ bool *pbFailed)"
);
// Note the parameter type pCallback is changed from void * to void **

const ptr: any[1] = [null];
const fail = [false];
if (
      SteamAPI_ManualDispatch_GetAPICallResult(
          pipe,
          completed.m_hAsyncCall, // call id
          koffi.as(ptr, "RemoteStorageFileReadAsyncComplete_t *"),
          completed.m_cubParam, // param size
          completed.m_iCallback, // callback type
          fail
      )
  ) {
    console.log(ptr[0]); // here we get an opaque pointer External [XXXXXXXXX]
    if (completed.m_iCallback === 1332) {
        const result = koffi.decode(ptr[0], "RemoteStorageFileReadAsyncComplete_t", completed.m_cubParam);
        // Above line will crash! and the console does not print any error log at all.
    }
}
```

Is there anything I am doing wrong? I am using koffi 2.2.4

**Comment by Koromix** [comment]
Not sure I understand; the header defines the parameter as `void *pCallback`. If you use `void **` it's different.

- **In the first case**, SteamAPI stores a struct in the memory pointerd to by pCallback (which is how the Steam API seems to work). Koffi prepares for this by allocating memory for `RemoteStorageFileReadAsyncComplete_t` and gives a pointer to this memory when calling the native function.
- **In the second one**, Koffi just reserve 8 bytes (size of a pointer on 64-bit platforms) and passes a pointer to this. There's not even enough memory, and when you decode things go wrong.

Now, you're right that Koffi is missing facility to decode an untyped buffer which makes this API annoying to use. I'll work on this in the next few days and let you know ;)

**Comment by insraq** [comment]
Thanks for the reply.

I need to modify the header from `void *pCallback` to `void **pCallback` so that koffi will set the external pointer, as I read from here: https://koffi.dev/changes#opaque-types (SQLite3 example)

If I didn't modify the definition, then ptr[0] is never set.

**Comment by Koromix** [comment]
I probably need to improve the documentation.

Opaque types refer to the case where an API (such as fopen, sqlite3_open_v2) return to you (either directly or through an output parameter) a pointer to an opaque type (a type allocated on the heap by the library, whose definition is not accessible outside the library).

Notice that in the SQLite3 example, the library declaration matches the one found in the Koffi 2.0 example:

- SQLite documentation: `int sqlite3_open_v2(const char *filename, sqlite3 **ppDb, int flags, const char *zVfs)`
- Koffi example: `lib.func('int sqlite3_open_v2(const char *, _Out_ sqlite3 **db, int, const char *)')` (except for the extra _Out_)

The case of the Steam API is different, it uses a polymorphic struct output parameter. When you use it from C or C++, you're supposed to malloc enough memory to hold the value (size is in m_cubParam) and the function will then fill this memory with the value. And then, you can cast the pointer to reinterpret this buffer as a struct. At least, that what I got from the header file: https://github.com/Facepunch/Facepunch.Steamworks/blob/4e7e0ef8c406bdf75f52d9fb1537713f75ce865b/Generator/steam_sdk/steam_api.h#L144-L152

Anyway, I've published **Koffi 2.2.6-beta.1** to help in your case. I haven't updated the documentation yet, but here is how I think you can use the Steam API (beware, I've make my own test cases and not tested with Steam API):

```js
// Start by installing koffi@beta (koffi@2.2.6-beta.1) or this won't work!!

// Back to void * because that's how the Steam API is defined
const SteamAPI_ManualDispatch_GetAPICallResult = steamLib.cdecl(
    "bool SteamAPI_ManualDispatch_GetAPICallResult(HSteamPipe hSteamPipe, SteamAPICall_t hSteamAPICall, _Out_ void *pCallback, int cubCallback, int iCallbackExpected, _Out_ bool *pbFailed)"
);

const data = Buffer.allocUnsafe(completed.m_cubParam);
const fail = [false];
if (
      SteamAPI_ManualDispatch_GetAPICallResult(
          pipe,
          completed.m_hAsyncCall, // call id
          data, // param buffer
          completed.m_cubParam, // param size
          completed.m_iCallback, // callback type
          fail
      )
  ) {
    console.log(data); // here we get the raw memory data

    if (completed.m_iCallback === 1332) {
        const result = koffi.decode(data, "RemoteStorageFileReadAsyncComplete_t");
        console.log(result); // here it is decoded
    }
}
```

PS: I don't know the first thing about TypeScript so you'll have to do this part yourself if needed somehow ^^

**Comment by insraq** [comment]
I think now I understand the problem - I thought in the 2nd example when I pass an **[External]** to `koffi.decode`, it will deref that pointer - I guess I misunderstood.

I can confirm that the code works for Steamworks API with 2.2.6-beta.1. Thanks for the quick response!

Also I read your earlier reply - and it uses `Buffer.allocUnsafe` but it fails randomly properly due to the fact that allocUnsafe will use buffer pool - I suppose for ffi purpose, `Buffer.alloc` should always be used instead?

**Comment by Koromix** [comment]
No, it should not make a difference. I changed it because allocUnsafe felt like a useless micro-optimization in this case.

How did it fail? Crash? Error?

**Comment by insraq** [comment]
If I use `allocUnsafe`, the buffer will not be correctly written (i.e. will get all 00s). The same code works if I use `alloc`

**Comment by Koromix** [comment]
Indeed, that's because my example is subtly wrong 😅

Here is the fixed one:

```js
// Start by installing koffi@beta (koffi@2.2.6-beta.1) or this won't work!!

// Back to void * because that's how the Steam API is defined
const SteamAPI_ManualDispatch_GetAPICallResult = steamLib.cdecl(
    "bool SteamAPI_ManualDispatch_GetAPICallResult(HSteamPipe hSteamPipe, SteamAPICall_t hSteamAPICall, _Out_ void *pCallback, int cubCallback, int iCallbackExpected, _Out_ bool *pbFailed)"
);

const data = Buffer.allocUnsafe(completed.m_cubParam);
const fail = [false];
if (
      SteamAPI_ManualDispatch_GetAPICallResult(
          pipe,
          completed.m_hAsyncCall, // call id
          data, // directly pass the Buffer/Uint8Array (and not the underlying buffer which is used for multiple allocations), that's where the problem came from
          completed.m_cubParam, // param size
          completed.m_iCallback, // callback type
          fail
      )
  ) {
    console.log(data); // here we get the raw memory data

    if (completed.m_iCallback === 1332) {
        const result = koffi.decode(data, "RemoteStorageFileReadAsyncComplete_t");
        console.log(result); // here it is decoded
    }
}
```

Also, update to **Koffi 2.2.6-beta.2** it'll work better ;)

**Comment by insraq** [comment]
Thanks, that's the issue.

I think this issue can be closed - I'll leave it up to you to decide whether you want to close it after you release the new version.

**Comment by Koromix** [comment]
Perfect, thanks :)
