### ISSUE TITLE
Convert void* to buffer

### ISSUE THREAD

**Issue by DannyDS** [Koromix/rygel#20]
I am trying to convert a void* to a byte array, it is quite large at around 3mb so I dont know if that has created any issues, I have tried decoding it at a shorter length but the frame is still empty.

Most of the things I have tried have ended up with the program crashing without an error code, I have tried creating a koffi.array of the correct length then trying koffi.decode into that but the array always stays empty.

The project currently is using FFI-Napi and works correctly, I have added what works with that library in one of the comments for comparison, can you see what I would need to change to do this?

    koffi.struct('CALLBACK_DATA', {
      'chan': 'int',
      'data': 'void*',
      'size': 'int',
      'width': 'int',
      'height': 'int',
    });

    const StreamCallbackFunction = koffi.callback('void StreamCallbackFunction(uint32 camera, CALLBACK_DATA data, uint32 length)');
 

    const RegisterFunctions = lib.func('void RegisterStreamCallback(void* obj, StreamCallbackFunction *callback)');

    StreamCallback = koffi.register(function(camera, data, length) {
    

     var frame = koffi.decode(data.data, 'uint8_t', data.size);

     //This is what we run on our current build using FFI-NAPI

    //var videoFramePtr = ref.readPointer(data.data.ref(), 0, data.size);
    //var videoFrame = Buffer.from(videoFramePtr);
  
    }, 'StreamCallbackFunction *');

Thanks,

**Comment by Koromix** [comment]
The `koffi.decode()` is a bit confusing indeed. In Koffi 2.2 (and ealier), it is only used to decode strings.

I've improved it in Koffi 2.3, currently in beta, you can install it with `koffi@2.3.0-beta.1` :) With this version, your code should work as expected.

For reference, here is the test code I've used to reproduce your issue:

```js
// gcc -shared -o decode.so decode.c

#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <string.h>

typedef struct CALLBACK_DATA {
    int chan;
    void *data;
    int size;
    int width;
    int height;
} CALLBACK_DATA;

typedef void StreamCallbackFunction(uint32_t camera, CALLBACK_DATA data, uint32_t length);

static StreamCallbackFunction *g_callback = NULL;

void RegisterStreamCallback(void *obj, StreamCallbackFunction *callback)
{
    g_callback = callback;
}

void TestCallback(int width, int height, int chan)
{
    CALLBACK_DATA data;
    memset(&data, 0, sizeof(data));

    data.chan = chan;
    data.width = width;
    data.height = height;
    data.size = chan * width * height;
    data.data = malloc(data.size);

    uint8_t *ptr = (uint8_t *)data.data;

    for (int i = 0; i < 8; i++) {
        for (int j = 0; j < data.size; j++)
            ptr[j] = j % (i + 1);
        g_callback(0, data, sizeof(data));
    }

    free(data.data);
}
```

```js
const koffi = require('/home/niels/Code/rygel/src/koffi/test/build/koffi.node');
const lib = koffi.load('./xxxx.so');

koffi.struct('CALLBACK_DATA', {
  'chan': 'int',
  'data': 'void*',
  'size': 'int',
  'width': 'int',
  'height': 'int',
});

const StreamCallbackFunction = koffi.callback('void StreamCallbackFunction(uint32 camera, CALLBACK_DATA data, uint32 length)');

const RegisterStreamCallback = lib.func('void RegisterStreamCallback(void* obj, StreamCallbackFunction *callback)');
const TestCallback = lib.func('void TestCallback(int width, int height, int chan)');

StreamCallback = koffi.register(function(camera, data, length) {
    let frame1 = koffi.decode(data.data, koffi.array('uint8_t', data.size));
    let frame2 = koffi.decode(data.data, 'uint8_t', data.size);

    console.log(frame1);
    console.log(frame2);
}, 'StreamCallbackFunction *');

RegisterStreamCallback(null, StreamCallback);

TestCallback(1, 4, 4);
TestCallback(2, 4, 4);

// Don't bother to unregister if you register at start and don't need to register dynamically a lot of callbacks ;)
koffi.unregister(StreamCallback);
```

**Comment by Koromix** [comment]
I've also improved the documentation to match the behavior in Koffi 2.3 (which will out of beta iun a couple days).

https://koffi.dev/callbacks#pointer-arguments

**Comment by Koromix** [comment]
Have you had a chance to try this change? :)

**Comment by DannyDS** [comment]
Hi, yes I have now tried it and worked perfectly.

Thank you
