### ISSUE TITLE
[koffi] declare union type in koffi

### ISSUE THREAD

**Issue by idoavni99** [Koromix/rygel#27]
How is it done? 

Example of what I'm trying to do:

`typedef struct
{
 double x;
 union ValuesType 
 {
     struct {double e,a,v} ua;
     struct {double h,l,s} uv;
  } values
} type_Definition`

**Comment by Koromix** [comment]
Also, I have a pretty good idea of how I want it to work already so expect this in a week :)

**Comment by idoavni99** [comment]
when can I Expect this?

**Comment by idoavni99** [comment]
also I wanna refine the example 

`typedef struct { double x; union ValuesType  { double vc[3];  struct {double e,a,v} ua; struct {double h,l,s} uv; } values } type_Definition`

**Comment by Koromix** [comment]
I'm working on it this week, you will be able to test it (in beta) during the week-end ;)
As you can see, the latest two commits are about unions :)

**Comment by idoavni99** [comment]
Hi man, just wondering, I'm trying to pass a null pointer to a function and
receive an error that the type is invalid.

How should i pass a null pointer of a primitive value?

**Comment by Koromix** [comment]
Hard to help without seeing the code :)

**Comment by idoavni99** [comment]
I made it work eventually.

**Comment by idoavni99** [comment]
I can't compile the project, could you send me a compiled version to test?

**Comment by Koromix** [comment]
Sorry, it's not ready yet. All of the code exists, but it's barely tested yet. So it's probably broken because there are lots of subtleties to take care of.

I'll publish a beta to NPM when it's ready for testing, hopefully this week-end!

**Comment by Koromix** [comment]
I've released Koffi 2.5.0 with union support.
Documentation is here: https://koffi.dev/unions
