### ISSUE TITLE
[koffi] Array definition missing from typescript file

### ISSUE THREAD

**Issue by idoavni99** [Koromix/rygel#29]
Also, how do you define a matrix using koffi.array? the docs aren't clear on that.

**Comment by Koromix** [comment]
Good catch! I've pushed a change to add `koffi.array()` to the TypeScript definition file.
Until I make a new release you can use it, you can [find the new definition in the repository](https://github.com/Koromix/rygel/blob/5e26a3e51728a1e29e7055fb38fa012152534ff2/src/koffi/src/index.d.ts).

As for the matrix question, I guess you mean multi-dimensional arrays in C?

I've not tested it, but in theory, for a 5x5 int matrix, you have two options depending on how you structure your JS data:

- Array of arrays (e.g. `[[1, 2, 3, 4, 5], ...]`): type should be `koffi.array(koffi.array('int', 5), 5)`
- Flat array with 25 values (e.g. `[1, 2, 3, 4... 25]`): type should be `koffi.array('int', 5)`

I cannot test this right now so let me know :)

**Comment by idoavni99** [comment]
thanks man !!!!!!!
