### ISSUE TITLE
[koffi] Is it possible to call c++ shared libraries

### ISSUE THREAD

**Issue by wanglin86769** [Koromix/rygel#31]
Hello, now I want to use functions from an existing module, but the module is implemented using C++ and it does not seem to provide an C interface. For example, the client.cpp source code is as follows,

https://github.com/mdavidsaver/pvxs/blob/master/src/pvxs/client.h
https://github.com/mdavidsaver/pvxs/blob/master/src/client.cpp

An example for how to use client.cpp is as follows,

https://github.com/mdavidsaver/pvxs/blob/master/example/simpleget.cpp

Is it possible to use functions from this C++ module? If not, is there any workaround, like writing a wrapper shared library to be called by C program?

**Comment by Koromix** [comment]
Hi!

Koffi is first and foremost a C FFI library.

It is in theory possible to call C++ shared libraries with it but:

- The C++ ABI contains a lot of extra stuff to deal with function overload (using name mangling), non-POD classes, etc.
- Non-POD types (inheritance, virtual functions) can use hidden pointers (such as the vtable) and stuff which Koffi does not know about.
- Methods have a hidden this parameter that is usually the first parameter, but can also use some weird platform-specific call conventions (such as __thiscall on 32-bit Windows).
- All of these details are platform-specific, in some cases compiler-specific, and less stable over time than the base C ABI of each platform.

Your best bet is to either :

- Use a wrapper C API (that internally uses the C++ ABI) itself.
- Make or find a Node module to use pvxs with this module, something based around N-API probably.
