### ISSUE TITLE
[koffi] Support for heap allocated returned values

### ISSUE THREAD

**Issue by lf94** [Koromix/rygel#34]
I've learned that in the event of a `thing* func()`, you will always get an `[External]` pointer reference, and cannot use it under any circumstance. The only way is to hope and pray there's an alternative method that has output parameters.

**Comment by lf94** [comment]
It worked with `__stdcall` actually. I'll close.

**Comment by lf94** [comment]
Nope, I was overly tired and blinded by exhaustion. This is still a problem.

**Comment by Koromix** [comment]
This really depends on how you have declared the return type and the function.

What does your code look like?

**Comment by lf94** [comment]
The ffi calls are like:

```js
const libfive_mesh = koffi.struct("libfive_mesh", {
    verts: "libfive_vec3*",
    tris: "libfive_tri*",
    tri_count: "uint32_t",
    vert_count: "uint32_t",
});
```

const libfive_tree_render_mesh = lib.func("libfive_mesh* libfive_tree_render_mesh(libfive_tree tree, libfive_region3 R, float res)");

And this *does* return an `[External]` reference, but when you do `thing.tri_count`, or any of the properties, they all return `undefined`.

It's for this https://github.com/libfive/libfive/blob/master/libfive/include/libfive.h#L356 .

This is the impl: https://github.com/libfive/libfive/blob/ae8ade5ada97af319f6ea07f06bd8242336171cd/libfive/src/libfive.cpp#L306

You can see it uses the C++ `new` keyword. For what it's worth, if I modify the library to use an `_Out_` parameter I can access properties as expected. It's only when the return type is `libfive_mesh*` that it doesn't work.

I'd like to take a moment to say thank you a ton for such an awesome FFI library! Checking out some of the code, it does *not* look trivial to write something like this!

**Comment by Koromix** [comment]
Okay I see :)

So the thing is, pointer arguments and return values are very ambiguous, and can mean many thing.

When it's an output parameter, Koffi uses the type of the JS value (such as an empty `{}` object) to know what to do.

For the return value, there's nothing to help Koffi. It could be an array of values, or one, or invalid, and how do you handle proper deallocation? The info is just not there.

But Koffi gives you a few tools, notably `koffi.decode()`. I haven't tested with libfive, but something like this should work:

```js
let m = libfive_tree_render_mesh(...);

let decoded = koffi.decode(m, 'libfive_mesh');
console.log(decoded);

// Do stuff

libfive_mesh_delete(m);
```

**Comment by lf94** [comment]
Yep, it became apparent to me that this is probably a difficult problem to solve within Koffi.

Ok, that should definitely do the trick, I'll let you know! Thank you a lot!

**Comment by Koromix** [comment]
You're right, the handling of pointer is split up in various sections and it's not easy to find.
A page dedicated to pointer conversions would probably help.

**Comment by lf94** [comment]
:o!! It worked! Perfect!

Thank you so much again for the help and for the awesome package!
