### ISSUE TITLE
uncaughtException: fs is not defined

### ISSUE THREAD

**Issue by gastonFrecceroNapse** [Koromix/rygel#36]
in ...\node_modules\koffi\src\koffi\src\index.js:42:1

```
// Development build
if (!fs.existsSync(filename)) {
    let dev_filename = __dirname + '/../build/koffi.node';

    if (fs.existsSync(dev_filename))
        filename = dev_filename;
}
```

**2023-02-27T18:44:17.073Z | uncaughtException: fs is not defined
ReferenceError: fs is not defined**

**Comment by gastonFrecceroNapse** [comment]
The solution is merged... waiting the release! =)

**Comment by Koromix** [comment]
Thanks!

For some reason it does not trigger anything on my Node version. Not sure why.

Anyway, about to release 2.3.7 :)
