### ISSUE TITLE
[koffi] Older glibc support

### ISSUE THREAD

**Issue by SarahAnnTolsma** [Koromix/rygel#38]
For a variety of reasons I'd like to use Koffi on an Ubuntu 18 LTS system, which does not come with the required version of glibc that Koffi uses (I believe Koffi uses 2.28, Ubuntu 18 comes with 2.26). Is it possible to support older glibc versions?

**Comment by Koromix** [comment]
Koffi was using `statx()`, which was introduced in *glibc 2.28*. I've changed the code to avoid this and in theory, you should be able to install *Koffi 2.3.10* on your old Ubuntu version.

Note that the prebuilt binaries in the NPM package probably don't work out of the box so the installation will rebuild Koffi.
