### ISSUE TITLE
[koffi] Having library that allocates and free buffers

### ISSUE THREAD

**Issue by rperrot** [Koromix/rygel#44]
Hi, 

I hava a C library that need to allocate and free char* buffers like that : 

```
int allocate( char ** str ) 
{
 * str = malloc( ...) 
}

int release( char ** str )
{
 free( *str );
}
```

It is used like : 

```
char* buff = NULL;
allocated( &buff );
...
release( &buff );
```

I tried to use it using koffi, I succeeded to allocated using a definition (_InOut_ char**): 

```
const allocate = lib.cdecl( 'allocate', 'int' , [koffi.inout( 'char**' )] );
var buff = [ null ]
allocate( buff );
```
However i cannot release it using : 

```
const release = lib.cdecl( 'release', 'int', [koffi.inout('char**') ]);
release( buff )
```

Here the pointer does not seems to the the same, so the internal free() leads to a segfault. 

I tried opaque or disposable type but without success. Is it possible with koffi ?

**Comment by Koromix** [comment]
Yeah, Koffi tries to be helpful with string conversion but sometimes it gets in the way.

You can skip the automatic stuff by declaring your types as `int8_t` or `uint8_t` instead of `char`. Then you have to decode the raw memory yourself.

I suggest you install **Koffi 2.3.15** (which I've just released) because it makes it a bit easier.

And then, this is how I've tested it based on your code:

```c
#include <stdlib.h>
#include <string.h>

void allocate(char **str)
{
    const char *TEXT = "Hello!";
    *str = malloc(strlen(TEXT) + 1);
    strcpy(*str, TEXT);
}

void release(char **str)
{
    free(*str);
```

```js
const koffi = require('koffi');
const lib = koffi.load('44.so');

const allocate = lib.func('void allocate(_Out_ uint8_t **str)');
const release = lib.func('void release(uint8_t **str)');

let str;
{
    let ptr = [null];

    allocate(ptr);
    str = koffi.decode(ptr[0], 'char', -1);
    release(ptr);
}

console.log(str);
```

**Comment by rperrot** [comment]
Sorry for the late answer. Just a few words to say it worked perfectly. Thanks !
