### ISSUE TITLE
[koffi] errno

### ISSUE THREAD

**Issue by yannisgu** [Koromix/rygel#45]
Hi

Thanks for the amazing library.

What I didn't manage to do is to get `errno`. I have limited C knowledge, so I'm a bit lost. 

I'm not sure how I would register a macro with koffi, but when I try to register the function `__geterrno` that also doesn't work.

Any idea how to read the errno value?

**Comment by Koromix** [comment]
Sure! Just use the newly released **Koffi 2.3.14** with `koffi.errno()`.

The documentation is here: https://koffi.dev/misc#posix-error-codes
