### ISSUE TITLE
[koffi] beginner question - how to declare on windows for user32 GetWindowThreadProcessId, FindWindowExA  correctly?

### ISSUE THREAD

**Issue by rscharnetzki** [Koromix/rygel#46]
With ffi-napi this works

example:

const ffi = require('ffi-napi');
const ref = require('ref-napi');

const user32 = new ffi.Library('user32', {
  'GetForegroundWindow': ['long', []],
  'FindWindowA': ['long', ['string', 'string']],
  'SetForegroundWindow': ['bool', ['int']],
  'FindWindowExA': ['int', ['int', 'int', 'string', 'string']],
  'GetWindowThreadProcessId': ['int', ['int', ref.refType('uint32')]],
});

currentHWnd = user32.FindWindowExA(0, currentHWnd, 'Chrome_WidgetWin_1', null);

---
I transformed this for koffi like this

const koffi = require('koffi');
const lib = koffi.load('user32.dll');

var user32 = {
    "GetForegroundWindow" : lib.stdcall("GetForegroundWindow", 'long', []),
    "FindWindowA": lib.stdcall( "FindWindowA", 'long', ['string', 'string']),
    'SetForegroundWindow': lib.stdcall('SetForegroundWindow','bool', ['int']),
    'FindWindowExA': lib.stdcall('FindWindowExA', 'int', ['int', 'int', 'string', 'string']),
    'GetWindowThreadProcessId': lib.stdcall('GetWindowThreadProcessId', 'int', ['int', 'uint32']),
};

currentHWnd = user32.FindWindowExA(0, currentHWnd, 'Chrome_WidgetWin_1', null);

But currentHWNd seems not get the right result?
Sorry for this newbie question. 
Thank you for any hint.

**Comment by Koromix** [comment]
There seems to be some code missing? Where is the currentHWnd value passed to FindWindowExA coming from?

**Comment by rscharnetzki** [comment]
thank you for coming back to me
i used the naive approach that worked with the old ffi library, thats how this variable is declared:

let currentHWnd = 0;

is that already wrong?

**Comment by rscharnetzki** [comment]
here is the complete function that works with ffi-napi that I am trying to replace with koffi:

const ffi = require('ffi-napi');
const ref = require('ref-napi');

const user32 = new ffi.Library('user32', {
  'GetForegroundWindow': ['long', []],
  'FindWindowA': ['long', ['string', 'string']],
  'SetForegroundWindow': ['bool', ['int']],
  'FindWindowExA': ['int', ['int', 'int', 'string', 'string']],
  'GetWindowThreadProcessId': ['int', ['int', ref.refType('uint32')]],
});

async function bringBrowserWindowToFront(browserProcessId) {
  let hWnd = 0;
  let currentHWnd = 0;

  do {
    currentHWnd = user32.FindWindowExA(0, currentHWnd, 'Chrome_WidgetWin_1', null);
    if (currentHWnd !== 0) {
      const processIdPtr = ref.alloc('uint32');
      user32.GetWindowThreadProcessId(currentHWnd, processIdPtr);
      const processId = processIdPtr.deref();

      if (processId === browserProcessId) {
        hWnd = currentHWnd;
      }
    }
  } while (currentHWnd !== 0 && hWnd === 0);

  if (hWnd !== 0) {
    user32.SetForegroundWindow(hWnd);
  }
}

module.exports = { focusChromeInstance , bringBrowserWindowToFront}`

**Comment by rscharnetzki** [comment]
With the help of :
https://stackoverflow.com/questions/73989309/js-koffi-call-dll-from-js
and this
https://github.com/xan105/node-ffi
I got it working.
Thank you for making koffi !

**Comment by Koromix** [comment]
Oh, nice :) Could you please post the working code if anyone else stumbles upon this? :)

**Comment by rscharnetzki** [comment]
Here it is as you requested:
```
const koffi = require('koffi');
const lib = koffi.load('user32.dll');

//helpfull:
//https://stackoverflow.com/questions/73989309/js-koffi-call-dll-from-js
//https://github.com/xan105/node-ffi

function alloc(type){
  return {
    pointer: Buffer.alloc(koffi.sizeof(type)),
    get: function(){ 
      return koffi.decode(this.pointer, type);
    }
  }
}

const Handle = koffi.opaque("Handle");

var user32 = {
    "GetForegroundWindow" : lib.stdcall("GetForegroundWindow", 'long', []),
    "FindWindowA": lib.stdcall( "FindWindowA", 'long', ['string', 'string']),
    'SetForegroundWindow': lib.stdcall('SetForegroundWindow','bool', ['int']),
    'FindWindowExA':  lib.stdcall("FindWindowExA","int", ["int", "int", 'string', 'string']),
    'GetWindowThreadProcessId': lib.stdcall('GetWindowThreadProcessId', 'int', ['int', koffi.out(koffi.pointer(Handle, 2))]),
};

async function bringBrowserWindowToFront(browserProcessId) {
  let hWnd = 0;
  let currentHWnd = 0;
  
  do {
    currentHWnd = user32.FindWindowExA(0,currentHWnd, 'Chrome_WidgetWin_1', null);
    if (currentHWnd !== 0) {
      const processIdPtr = alloc("uint16");
      let result = user32.GetWindowThreadProcessId(currentHWnd, processIdPtr.pointer)
      if (processIdPtr.get() === browserProcessId) {
        hWnd = currentHWnd;
      }
    }
  } while (currentHWnd !== 0 && hWnd === 0);

  if (hWnd !== 0) {
    user32.SetForegroundWindow(hWnd);
  }
}

module.exports = { bringBrowserWindowToFront}
```

**Comment by Koromix** [comment]
Thanks! :)

**Comment by Koromix** [comment]
It works but it's slightly incorrect.

First, Windows process IDs are not opaque, they are DWORD integers (which is basically the same as `uint32_t`). Secondly, you can use a simpler and more Koffi-idiomatic way to get back a primitive output value.

So I've adapted your code and made an example based on it in the documentation.

```js
const koffi = require('koffi');
const lib = koffi.load('user32.dll');

const user32 = {
    'GetForegroundWindow' : lib.stdcall('GetForegroundWindow', 'long', []),
    'FindWindowA': lib.stdcall( 'FindWindowA', 'long', ['string', 'string']),
    'SetForegroundWindow': lib.stdcall('SetForegroundWindow','bool', ['int']),
    'FindWindowExA':  lib.stdcall('FindWindowExA','int', ['int', 'int', 'string', 'string']),
    // The output parameter of GetWindowThreadProcessId is a DWORD value, which is basically uint32_t
    'GetWindowThreadProcessId': lib.stdcall('GetWindowThreadProcessId', 'int', ['int', koffi.out(koffi.pointer('uint32_t'))]),
};

async function bringBrowserWindowToFront(browserProcessId) {
  let hWnd = 0;
  let currentHWnd = 0;

  do {
    currentHWnd = user32.FindWindowExA(0,currentHWnd, 'Chrome_WidgetWin_1', null);
    if (currentHWnd !== 0) {
      // Use a single-element array for simple output values, as documented here:
      // https://koffi.dev/calls#output-parameters#primitive-value
      const processIdPtr = [null];
      let result = user32.GetWindowThreadProcessId(currentHWnd, processIdPtr);
      if (processIdPtr[0] === browserProcessId) {
        hWnd = currentHWnd;
      }
    }
  } while (currentHWnd !== 0 && hWnd === 0);

  if (hWnd !== 0) {
    user32.SetForegroundWindow(hWnd);
  }
}

module.exports = { bringBrowserWindowToFront };
```

And here is the new example in the documentation: https://koffi.dev/calls#primitive-value
