### ISSUE TITLE
Koffi: Any way to unload a loaded lib?

### ISSUE THREAD

**Issue by jeremywho** [Koromix/rygel#49]
I couldn't find a why to explicitly unload a previously loaded library. 

Is there a mechanism currently available to do this?

**Comment by Koromix** [comment]
Koffi automatically unloads the library once all references to it are gone and the GC actually cleans it up.

But as of Koffi 2.3.19 you cannot explicitly unload a library. In Koffi 2.3.20, which will be available shortly, you can!

**Comment by Koromix** [comment]
Koffi 2.3.20 is released :)

Please read the documentation about loading/unloading libraries here: https://koffi.dev/functions#loading-libraries (and the note related to unloading)
