### ISSUE TITLE
[koffi] koffi.decode support specify encoding

### ISSUE THREAD

**Issue by joyexpr** [Koromix/rygel#58]
koffi.decode has no encoding option, like 'gbk', hope to be supported

**Comment by Koromix** [comment]
I've made changes in Koffi 2.5.5 (just released) to make this easier, so you will have to update before trying the example below.

Support of non-UTF8 (and non-UTF16) encodings is outside of the perimeter of Koffi.

However, here is how you can combine Koffi 2.5.5 and iconv-lite to decode GBK strings:

```c
// Build with: gcc -shared -o gbk.so gbk.c

const char *GetString()
{
    // GBK encoding of ン
    return "\xA5\xF3";
}
```

```js
// npm install koffi iconv-lite

const koffi = require('koffi');
const iconv = require('iconv-lite');

const lib = koffi.load('./gbk.so');
const GetString = lib.func('const uint8_t *GetString()');

let ptr = GetString();

// Transform ptr to a typed array (length is detected automatically with strlen) with koffi.decode()...
let buf = koffi.decode(ptr, 'uint8_t', -1);

// ...and then decode it with iconv
let str = iconv.decode(buf, 'gbk');

// It works!
console.log(str);
```

**Comment by joyexpr** [comment]
how if the result  ptr is  input param of the func, but the return ?

**Comment by Koromix** [comment]
Can you show me the code so I can understand better?

**Comment by joyexpr** [comment]
below is my code, it worked.

```
const read = lib.func(funcRead)
const readAsync = promisify(read.async)

const resultBuf = Buffer.alloc(1000000, '0') // but I don't know the safety max length, 1000000 may too small
await readAsync(param1, param2, resultBuf)

let resultStr = iconv.decode(resultBuf, 'gbk') 
// in my case, the result is json string. But in other case, how to simply extract the resultStr
resultStr = resultStr.substring(0, resultStr.lastIndexOf('}') + 1)
const resultJson = JSON.parse(resultStr)

```

but it has 2 weaknesses as comments above. 

any better or simpler solution?

**Comment by Koromix** [comment]
For the first point, that depends on the API you're calling. What does its documentation say about how much space to reserve?

For the second point, I think you need to use something like this:

```js
let str = iconv.decode(resultBuf.subarray(0, resultBuf.indexOf(0)), 'gbk');
console.log(str);
```

**Comment by joyexpr** [comment]
The api document doesn't tell, I was just not sure is it possible to automatically adapted.

Thanks for the response. 

By the way, koffi is awesome.  I recommended it to a lot of my developer
 friends.  It may be better to seperate koffi from the mono repository for getting more stars,   I read your reason about mono repository.

**Comment by Koromix** [comment]
Thanks :)

I will keep the monorepo no matter what, because it's just a much better way for me to work. Version control for me is just about version control of my code. I lament the fact that git and especially GitHub popularized the "one project = one repository" but that's the world we live in :)

Maybe I could make a pseudo-repo for Koffi, without anything except a README (indicating where the source actually lives and why I do monorepo), and keep the Koffi issues there?

Do you think this would make sense?
