### ISSUE TITLE
Base64 

### ISSUE THREAD

**Issue by codigosistemas** [Koromix/rygel#7]
Hi, is there a way to retrieve a base64 from a function into an array of str?

**Comment by Koromix** [comment]
Hi, could you be more specific? Is this about calling C with Koffi, or something else?

**Comment by codigosistemas** [comment]
Yes, calling a C function, the return is a base64 string, but the limit of array of str is 4095 chars.

**Comment by Koromix** [comment]
It's hard to help you without more information.

Can you provide the prototype of the C function you're trying to call, and the Koffi/Javascript code you're using ?

**Comment by codigosistemas** [comment]
`const koffi = require('koffi');

let path = resolve(__dirname,'libacbrnfe64.so');
const lib = koffi.load(path);

let responseBase64 =  koffi.struct('responseBase64', {
  pdf:  koffi.array('char', 4095)
});

const NFE_GetPDF = lib.func('int NFE_GetPDF(HANDLE *handle, Out responseBase64 *sResponse, str esSize)');

let response_status = 2;
let response = [null];
let size = '512000';

response_status = NFE_GetPDF(handlelib[0], response, size);
console.log(response);`

The error if is increment the array size is: free(): invalid next size (normal)

**Comment by Koromix** [comment]
How is the function declared on the C (or C++ side). Do you have the original C prototype of the function `NFE_GetPDF`, and the original declaration of `struct responseBase64`?

**Comment by codigosistemas** [comment]
The return of function contains a long array of string, for example, 64000 characters, but the koffi.array type 'char' only supports 4095 characters. A example with ffi-napi, the return is aloccated in a buffer with this size.

**Comment by Koromix** [comment]
Version 2.1.4 will allow bigger types, up to 64 MiB, I'll make the release on NPM tomorrow (can't right now because of bad internet).

**Comment by Koromix** [comment]
Koffi 2.1.4 is on NPM (changelog here: https://koffi.dev/changes) hopefully that fixes your issue :)

**Comment by codigosistemas** [comment]
Thanks Koromix! It's perfect, worked very well, greetings from Brazil!
