### ISSUE TITLE
Meestic: Cannot find Mystic Light HID device (1462:1562, 1462:1563 or 1462:1564)

### ISSUE THREAD

**Issue by MartinSalinas98** [Koromix/rygel#71]

**Comment by Koromix** [comment]
You are probably on Linux, can you run `lsusb -v` in a console and post the results here?

**Comment by MartinSalinas98** [comment]
Sorry, I was mid typing the issue when I accidentally pressed Enter.
I'm on a MSI STEALTH 16 Studio A13V, on Ubuntu, I just realised meestic is meant fir Delta 15, so that's probably my issue.
Sorry to bother

**Comment by Koromix** [comment]
Yes but it might work the same, just with a different VID:PID pair, which I could easily add to meestic.

So post the result of `lsusb` anyway, to see if it might be the case.

**Comment by MartinSalinas98** [comment]
Sure! Here it is:
```
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 007: ID 046d:c077 Logitech, Inc. M105 Optical Mouse
Bus 003 Device 004: ID 1038:113a SteelSeries ApS SteelSeries KLC
Bus 003 Device 003: ID 27c6:6094 Shenzhen Goodix Technology Co.,Ltd. Goodix USB2.0 MISC
Bus 003 Device 005: ID 8087:0033 Intel Corp. 
Bus 003 Device 002: ID 5986:213a Acer, Inc FHD Camera
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by Koromix** [comment]
Okay, sorry, I've just looked and it's a very different feature set from the Delta 15.

I'd love to support your laptop but it's hard to work on it without having it :) If I win the lottery I'll come back to this 😅
