### ISSUE TITLE
Error: Cannot determine default GCC architecture

### ISSUE THREAD

**Issue by svenk** [Koromix/rygel#82]
When invoking `bootstrap.sh` at a fresh git clone, I get

```
Bootstrapping felix with Clang...
[ around 50 secs... ]
Error: Cannot determine default GCC architecture
```

Can I tell *felix* to just use GCC? This is arch linux with GCC 14 and CLANG 17 on ordinary x86_64-pc-linux-gnu.

**Comment by Koromix** [comment]
What does a call to `gcc -v` return on your system?

**Comment by svenk** [comment]
So apparently this kind of output comes from `bin/BootstrapFelix/felix`. I tried to remove the Clang from the autodetection but also the GCC-variant returns `Error: Cannot determine default GCC architecture` 

Here comes

```
% LANG=C LC_ALL=C gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --enable-languages=ada,c,c++,d,fortran,go,lto,m2,objc,obj-c++,rust --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://gitlab.archlinux.org/archlinux/packaging/packages/gcc/-/issues --with-build-config=bootstrap-lto --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-libstdcxx-backtrace --enable-link-serialization=1 --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-werror
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 14.1.1 20240522 (GCC) 
```

**Comment by Koromix** [comment]
Any better with the latest commit I've just pushed?

**Comment by svenk** [comment]
Pulling to 263b6bb54 and bootstrapping felix with GCC in fact improves things and now the build now runs. Haven't tested clang yet.

So this was probably really an issue with the localization. What a luck I did not strip the `LC_ALL=C` stuff in my post to the issue!

**Comment by svenk** [comment]
Can confirm that it also works now with clang:

```bash
$ git checkout src/felix/bootstrap.sh # undoing my uncommenting of clang
$ rm -f felix bin/ # resetting the boostrapping code and all builds
$ ./bootstrap.sh
Bootstrapping felix with Clang...
[... suceeds ...]
```

Beautiful code and infrastructure. A bit bizzare, with all homebrewn make system, but just works :-)

**Comment by svenk** [comment]
After all, thank you for providing this code, in particular as public domain and also providing so quick help and fixes via github issues!
